// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: open-ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenAI_CreateChat_FullMethodName = "/server.OpenAI/CreateChat"
)

// OpenAIClient is the client API for OpenAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenAIClient interface {
	CreateChat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResp], error)
}

type openAIClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenAIClient(cc grpc.ClientConnInterface) OpenAIClient {
	return &openAIClient{cc}
}

func (c *openAIClient) CreateChat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OpenAI_ServiceDesc.Streams[0], OpenAI_CreateChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatReq, ChatResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenAI_CreateChatClient = grpc.ServerStreamingClient[ChatResp]

// OpenAIServer is the server API for OpenAI service.
// All implementations must embed UnimplementedOpenAIServer
// for forward compatibility.
type OpenAIServer interface {
	CreateChat(*ChatReq, grpc.ServerStreamingServer[ChatResp]) error
	mustEmbedUnimplementedOpenAIServer()
}

// UnimplementedOpenAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenAIServer struct{}

func (UnimplementedOpenAIServer) CreateChat(*ChatReq, grpc.ServerStreamingServer[ChatResp]) error {
	return status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}
func (UnimplementedOpenAIServer) mustEmbedUnimplementedOpenAIServer() {}
func (UnimplementedOpenAIServer) testEmbeddedByValue()                {}

// UnsafeOpenAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenAIServer will
// result in compilation errors.
type UnsafeOpenAIServer interface {
	mustEmbedUnimplementedOpenAIServer()
}

func RegisterOpenAIServer(s grpc.ServiceRegistrar, srv OpenAIServer) {
	// If the following call pancis, it indicates UnimplementedOpenAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenAI_ServiceDesc, srv)
}

func _OpenAI_CreateChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OpenAIServer).CreateChat(m, &grpc.GenericServerStream[ChatReq, ChatResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenAI_CreateChatServer = grpc.ServerStreamingServer[ChatResp]

// OpenAI_ServiceDesc is the grpc.ServiceDesc for OpenAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.OpenAI",
	HandlerType: (*OpenAIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateChat",
			Handler:       _OpenAI_CreateChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "open-ai.proto",
}
