// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: open-ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenAI_CrawlMetadataAsync_FullMethodName = "/collector.OpenAI/CrawlMetadataAsync"
)

// OpenAIClient is the client API for OpenAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenAIClient interface {
	CrawlMetadataAsync(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type openAIClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenAIClient(cc grpc.ClientConnInterface) OpenAIClient {
	return &openAIClient{cc}
}

func (c *openAIClient) CrawlMetadataAsync(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OpenAI_CrawlMetadataAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenAIServer is the server API for OpenAI service.
// All implementations must embed UnimplementedOpenAIServer
// for forward compatibility.
type OpenAIServer interface {
	CrawlMetadataAsync(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	mustEmbedUnimplementedOpenAIServer()
}

// UnimplementedOpenAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenAIServer struct{}

func (UnimplementedOpenAIServer) CrawlMetadataAsync(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlMetadataAsync not implemented")
}
func (UnimplementedOpenAIServer) mustEmbedUnimplementedOpenAIServer() {}
func (UnimplementedOpenAIServer) testEmbeddedByValue()                {}

// UnsafeOpenAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenAIServer will
// result in compilation errors.
type UnsafeOpenAIServer interface {
	mustEmbedUnimplementedOpenAIServer()
}

func RegisterOpenAIServer(s grpc.ServiceRegistrar, srv OpenAIServer) {
	// If the following call pancis, it indicates UnimplementedOpenAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenAI_ServiceDesc, srv)
}

func _OpenAI_CrawlMetadataAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenAIServer).CrawlMetadataAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenAI_CrawlMetadataAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenAIServer).CrawlMetadataAsync(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenAI_ServiceDesc is the grpc.ServiceDesc for OpenAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collector.OpenAI",
	HandlerType: (*OpenAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlMetadataAsync",
			Handler:    _OpenAI_CrawlMetadataAsync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "open-ai.proto",
}
